worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 3000;
        server_name localhost;

        # Serve Frontend Static Files
        root /usr/share/nginx/html;
        index desktop.html; # O router javascript lida com isso se entrarmos em /

        # Redirecionamento da raiz pro router index.html
        location = / {
            try_files /index.html =404;
        }

        # Demais arquivos estáticos
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Proxy Reverso para a API (Node.js)
        location /api/ {
            proxy_pass http://app:3000/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Suporte a Server-Sent Events (Chat Stream)
            proxy_set_header Connection '';
            proxy_http_version 1.1;
            chunked_transfer_encoding off;
            proxy_buffering off;
            proxy_cache off;
        }
    }
}
